apiVersion: 1

datasources:
  - name: IndustrialAI_SQLServer
    uid: industrial-ai-mssql
    type: mssql
    access: proxy
    url: sqlserver:1433
    database: Industrail_AI
    user: sa
    secureJsonData:
      password: "IndustrialAI#2026"
    jsonData:
      authenticationType: SQL Server Authentication
      encrypt: "false"
    isDefault: true
    editable: true
